In [1]:
l = [23245, 27, 546, 215, -1234]

In [2]:
l

[23245, 27, 546, 215, -1234]

In [6]:
import numpy as np

In [7]:
a = np.array(l)

In [8]:
a

array([23245,    27,   546,   215, -1234])

In [9]:
b = np.array([12, 455, 63.3, True, "abc"])

In [10]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [11]:
l.pop()

-1234

In [12]:
l

[23245, 27, 546, 215]

In [13]:
a.mean()

4559.8000000000002

In [73]:
# -----------------

In [78]:
a

array([23245,    27,   546,   215, -1234])

In [79]:
a[2:]

array([  546,   215, -1234])

In [80]:
a[2:4]

array([546, 215])

In [81]:
b = a[2:4]

In [82]:
b

array([546, 215])

In [83]:
b[0]

546

In [84]:
b[:] = 111

In [85]:
b

array([111, 111])

In [86]:
a

array([23245,    27,   111,   111, -1234])

In [87]:
c = a.copy()

In [88]:
c

array([23245,    27,   111,   111, -1234])

In [89]:
c[0] = 0

In [90]:
c

array([    0,    27,   111,   111, -1234])

In [91]:
a

array([23245,    27,   111,   111, -1234])